[package]
name = "indel_check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.13"

[profile.release]
strip = true  # Automatically strip symbols from the binary.